apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vufx3zyrj-java-springboot
  janus-idp.io/tekton: vufx3zyrj-java-springboot
  backstage.io/kubernetes-id: vufx3zyrj-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vufx3zyrj-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
