apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vufx3zyrj-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vufx3zyrj-java-springboot-gitops